# Generated by Django 5.2.13 on 2026-04-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='full name')),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_date', models.DateField(verbose_name='preferred date')),
                ('address', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=16)),
                ('service', models.CharField(choices=[('leaking_pipe', 'Leaking Pipe'), ('blocked_drain', 'Blocked Drain'), ('water_heater', 'Water Heater'), ('toilet_repair', 'Toilet Repair'), ('burst_pipe', 'Burst Pipe'), ('bathroom_kitchen', 'Bathroom / Kitchen'), ('gas_plumbing', 'Gas Plumbing'), ('general', 'General Maintenance'), ('other', 'Other')], max_length=32)),
                ('timeslot', models.CharField(choices=[('7am-9am', '7am-9am'), ('9am-11am', '9am-11am'), ('11am-1pm', '11am-1pm'), ('1pm-3pm', '1pm-3pm'), ('3pm-5pm', '3pm-5pm'), ('5pm-7pm', '5pm-7pm')], max_length=16, verbose_name='preferred time slot')),
                ('description', models.TextField()),
                ('is_emergency', models.BooleanField(default=False, verbose_name='emergency')),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('booked', 'Booked'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=16)),
                ('admin_notes', models.TextField(blank=True, verbose_name='admin notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'booking enquiry',
                'verbose_name_plural': 'booking enquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='trades_book_created_659b1c_idx'), models.Index(fields=['preferred_date'], name='trades_book_preferr_4aa601_idx'), models.Index(fields=['status'], name='trades_book_status_b5c823_idx'), models.Index(fields=['is_emergency'], name='trades_book_is_emer_5cf961_idx')],
            },
        ),
    ]
