# Generated by Django 5.2.13 on 2026-04-29 15:27

import django.db.models.deletion
from django.db import migrations, models


def seed_default_business(apps, schema_editor):
    BusinessProfile = apps.get_model("trades", "BusinessProfile")
    ServiceOffering = apps.get_model("trades", "ServiceOffering")
    Testimonial = apps.get_model("trades", "Testimonial")
    TrustIndicator = apps.get_model("trades", "TrustIndicator")

    business, _ = BusinessProfile.objects.get_or_create(
        business_name="FlowPro Plumbing",
        defaults={"is_active": True},
    )

    for index, label in enumerate(
        [
            "Local & Reliable",
            "Emergency Call-outs",
            "Clear Upfront Advice",
            "Tidy Workmanship",
            "Fully Insured*",
        ],
        start=1,
    ):
        TrustIndicator.objects.get_or_create(
            business=business,
            label=label,
            defaults={"sort_order": index},
        )

    for index, service in enumerate(
        [
            ("Leak Repairs", "Fast fault-finding and repair work.", "icon-wrench"),
            ("Shower & Bath", "Installation, servicing, and upgrades.", "icon-shower"),
            ("Toilet Repair", "Cisterns, leaks, flushes, and fittings.", "icon-wrench"),
            ("Drain Unblocking", "Blocked sinks, baths, and external drains.", "icon-droplet"),
            ("Water Heaters", "Repairs, replacements, and checks.", "icon-flame"),
            ("Bathroom Fitting", "Planned upgrades and full refits.", "icon-home"),
        ],
        start=1,
    ):
        title, description, icon = service
        ServiceOffering.objects.get_or_create(
            business=business,
            title=title,
            defaults={
                "description": description,
                "icon": icon,
                "sort_order": index,
            },
        )

    for index, testimonial in enumerate(
        [
            (
                "Arrived quickly, explained the problem clearly, and left the place spotless. Very professional from start to finish.",
                "Sarah J.",
                "Local Customer",
            ),
            (
                "Great communication and fair pricing. The booking process was simple and the repair was completed the same day.",
                "James C.",
                "Homeowner",
            ),
            (
                "Reliable, tidy, and honest. Exactly what you want from a local plumber.",
                "David O.",
                "Local Customer",
            ),
        ],
        start=1,
    ):
        quote, author_name, author_label = testimonial
        Testimonial.objects.get_or_create(
            business=business,
            author_name=author_name,
            defaults={
                "quote": quote,
                "author_label": author_label,
                "rating": 5,
                "sort_order": index,
            },
        )


def unseed_default_business(apps, schema_editor):
    BusinessProfile = apps.get_model("trades", "BusinessProfile")
    BusinessProfile.objects.filter(business_name="FlowPro Plumbing").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='FlowPro Plumbing', max_length=120)),
                ('brand_first', models.CharField(default='Flow', max_length=40)),
                ('brand_second', models.CharField(default='Pro', max_length=40)),
                ('tagline', models.CharField(default='Premium local plumbing services - fast, clear, and reliable.', max_length=180)),
                ('meta_description', models.TextField(default='Premium local plumbing services with fast response, online booking, emergency call-outs, leak repairs, bathroom fitting, and drain unblocking.')),
                ('hero_badge', models.CharField(default='Trusted local plumbing specialists', max_length=120)),
                ('hero_heading_line_one', models.CharField(default='Premium Plumbing', max_length=80)),
                ('hero_heading_line_two', models.CharField(default='Without the Stress', max_length=80)),
                ('hero_body', models.TextField(default='Reliable local plumbers for urgent repairs, leaks, drains, bathrooms, and general maintenance. Clear communication, tidy workmanship, and fast call-backs.')),
                ('phone_display', models.CharField(default='0161 555 0123', max_length=40)),
                ('phone_href', models.CharField(default='+441615550123', max_length=40)),
                ('email', models.EmailField(default='hello@flowpro-plumbing.co.uk', max_length=254)),
                ('service_area', models.CharField(default='Serving Manchester & surrounding areas', max_length=160)),
                ('owner_name', models.CharField(default='Mark Henderson', max_length=120)),
                ('owner_role', models.CharField(default='Local Plumbing Specialist', max_length=120)),
                ('about_label', models.CharField(default='Meet Your Plumber', max_length=80)),
                ('about_text', models.TextField(default="FlowPro is built around a simple promise: clear communication, fair pricing, and respect for your home. This section can be replaced with the real business owner's story, qualifications, guarantees, and service area.")),
                ('services_label', models.CharField(default='Our Services', max_length=80)),
                ('services_title', models.CharField(default='Complete Plumbing Solutions', max_length=120)),
                ('services_subtitle', models.TextField(default='A flexible service template for local trades: quick repairs, planned installs, maintenance visits, and emergency call-outs.')),
                ('booking_label', models.CharField(default='Book a Visit', max_length=80)),
                ('booking_title', models.CharField(default='Schedule Your Service', max_length=120)),
                ('booking_subtitle', models.TextField(default='Send a booking enquiry and the team will confirm availability. For urgent issues, call directly for the fastest response.')),
                ('reviews_label', models.CharField(default='Testimonials', max_length=80)),
                ('reviews_title', models.CharField(default='What Local Customers Say', max_length=120)),
                ('reviews_subtitle', models.TextField(default='Use this area for real verified customer reviews once the business has approved them.')),
                ('footer_disclaimer', models.TextField(default='Replace claims, reviews, insurance details, and qualifications with verified client information.')),
                ('hero_image', models.ImageField(blank=True, upload_to='business/hero/')),
                ('services_image', models.ImageField(blank=True, upload_to='business/services/')),
                ('about_image', models.ImageField(blank=True, upload_to='business/about/')),
                ('booking_image', models.ImageField(blank=True, upload_to='business/booking/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'business profile',
                'verbose_name_plural': 'business profiles',
                'ordering': ['-is_active', 'business_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=160)),
                ('icon', models.CharField(choices=[('icon-wrench', 'Wrench'), ('icon-shower', 'Shower'), ('icon-droplet', 'Droplet'), ('icon-flame', 'Flame'), ('icon-home', 'Home')], default='icon-wrench', max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_offerings', to='trades.businessprofile')),
            ],
            options={
                'verbose_name': 'service offering',
                'verbose_name_plural': 'service offerings',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=80)),
                ('author_label', models.CharField(default='Local Customer', max_length=80)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='trades.businessprofile')),
            ],
            options={
                'verbose_name': 'testimonial',
                'verbose_name_plural': 'testimonials',
                'ordering': ['sort_order', 'author_name'],
            },
        ),
        migrations.CreateModel(
            name='TrustIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trust_indicators', to='trades.businessprofile')),
            ],
            options={
                'verbose_name': 'trust indicator',
                'verbose_name_plural': 'trust indicators',
                'ordering': ['sort_order', 'label'],
            },
        ),
        migrations.RunPython(seed_default_business, unseed_default_business),
    ]
