# Generated by Django 5.2.13 on 2026-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0003_testimonial_created_at_testimonial_source_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingenquiry',
            name='testimonial_job_label',
            field=models.CharField(blank=True, help_text='Customer-facing completed job label shown on review cards, e.g. Bathroom tap repair.', max_length=140, verbose_name='testimonial job label'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='job_label',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
