# Generated by Django 5.2.13 on 2026-04-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0004_bookingenquiry_testimonial_job_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='International WhatsApp number. Use digits or + format, e.g. +441615550123.', max_length=32),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='whatsapp_prefilled_message',
            field=models.TextField(blank=True, default='Hi, I would like to enquire about plumbing services.', help_text='Message prefilled when a customer opens WhatsApp chat.'),
        ),
    ]
