# Generated by Django 5.2.13 on 2026-05-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0005_businessprofile_whatsapp_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='booking/diagnostics/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_images', to='trades.bookingenquiry')),
            ],
            options={
                'verbose_name': 'booking diagnostic image',
                'verbose_name_plural': 'booking diagnostic images',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
