# Generated by Django 5.2.13 on 2026-05-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0006_bookingimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='bank_sort_code',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Company logo used on invoice PDFs and emails.', upload_to='business/logo/'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='service_postcodes',
            field=models.CharField(blank=True, help_text='Comma-separated postcode prefixes this business serves, e.g. M,SK,WA.', max_length=300),
        ),
    ]
