# Generated by Django 5.2.13 on 2026-05-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0007_businessprofile_logo_bank_postcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='about_label',
            field=models.CharField(default='Meet Your Tradesperson', max_length=80),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='about_text',
            field=models.TextField(default="Built around a simple promise: clear communication, fair pricing, and respect for your home. This section can be replaced with the real business owner's story, qualifications, guarantees, and service area."),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='brand_first',
            field=models.CharField(default='Local', max_length=40),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='business_name',
            field=models.CharField(default='Your Local Tradesperson', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='email',
            field=models.EmailField(default='hello@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='hero_badge',
            field=models.CharField(default='Trusted local trade specialists', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='hero_body',
            field=models.TextField(default='Reliable local tradespeople for urgent repairs, installations, and general maintenance. Clear communication, tidy workmanship, and fast call-backs.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='hero_heading_line_one',
            field=models.CharField(default='Quality Workmanship', max_length=80),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='meta_description',
            field=models.TextField(default='Quality local trade services with fast response, online booking, emergency call-outs, repairs, installations, and maintenance.'),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='owner_name',
            field=models.CharField(default='Your Name Here', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='owner_role',
            field=models.CharField(default='Local Trades Specialist', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='service_area',
            field=models.CharField(default='Serving your local area', max_length=160),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='services_title',
            field=models.CharField(default='Our Services', max_length=120),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='tagline',
            field=models.CharField(default='Quality local trade services — fast, clear, and reliable.', max_length=180),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='whatsapp_prefilled_message',
            field=models.TextField(blank=True, default='Hi, I would like to enquire about your services.', help_text='Message prefilled when a customer opens WhatsApp chat.'),
        ),
    ]
