# Generated by Django 5.2.13 on 2026-05-03 17:41

from django.db import migrations

_GENERIC_DEFAULTS = {
    "business_name": "Your Local Tradesperson",
    "brand_first": "Local",
    "brand_second": "Pro",
    "tagline": "Quality local trade services — fast, clear, and reliable.",
    "meta_description": (
        "Quality local trade services with fast response, online booking, "
        "emergency call-outs, repairs, installations, and maintenance."
    ),
    "hero_badge": "Trusted local trade specialists",
    "hero_heading_line_one": "Quality Workmanship",
    "hero_heading_line_two": "Without the Stress",
    "hero_body": (
        "Reliable local tradespeople for urgent repairs, installations, "
        "and general maintenance. Clear communication, tidy workmanship, and "
        "fast call-backs."
    ),
    "phone_display": "0161 555 0123",
    "phone_href": "+441615550123",
    "email": "hello@example.com",
    "service_area": "Serving your local area",
    "owner_name": "Your Name Here",
    "owner_role": "Local Trades Specialist",
    "about_label": "Meet Your Tradesperson",
    "about_text": (
        "Built around a simple promise: clear communication, fair "
        "pricing, and respect for your home. This section can be replaced with "
        "the real business owner's story, qualifications, guarantees, and "
        "service area."
    ),
    "services_label": "Our Services",
    "services_title": "Our Services",
    "services_subtitle": (
        "A flexible service template for local trades: quick repairs, planned "
        "installs, maintenance visits, and emergency call-outs."
    ),
    "booking_label": "Book a Visit",
    "booking_title": "Schedule Your Service",
    "booking_subtitle": (
        "Send a booking enquiry and the team will confirm availability. For "
        "urgent issues, call directly for the fastest response."
    ),
    "reviews_label": "Testimonials",
    "reviews_title": "What Local Customers Say",
    "reviews_subtitle": (
        "Use this area for real verified customer reviews once the "
        "business has approved them."
    ),
    "footer_disclaimer": (
        "Replace claims, reviews, insurance details, and qualifications with "
        "verified client information."
    ),
}


def update_seeded_business(apps, schema_editor):
    BusinessProfile = apps.get_model("trades", "BusinessProfile")
    updated = BusinessProfile.objects.filter(
        business_name="FlowPro Plumbing"
    ).update(**_GENERIC_DEFAULTS)
    if updated:
        print(f"  Updated {updated} seeded BusinessProfile(s) to generic defaults.")


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("trades", "0008_trade_agnostic_defaults"),
    ]

    operations = [
        migrations.RunPython(update_seeded_business, noop),
    ]
