# Generated by Django 5.2.13 on 2026-06-27 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0011_legalpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingenquiry',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_enquiries', to='trades.businessprofile'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='closing_time',
            field=models.TimeField(default='18:00', help_text='If current time is past this, ASAP defaults to the next working day.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='default_slot_capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum bookings per time slot before the slot is marked unavailable.'),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='opening_time',
            field=models.TimeField(default='08:00', help_text='Earliest time slots considered available for ASAP booking.'),
        ),
        migrations.CreateModel(
            name='TimeSlotAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeslot', models.CharField(choices=[('7am-9am', '7am-9am'), ('9am-11am', '9am-11am'), ('11am-1pm', '11am-1pm'), ('1pm-3pm', '1pm-3pm'), ('3pm-5pm', '3pm-5pm'), ('5pm-7pm', '5pm-7pm')], max_length=16)),
                ('capacity', models.PositiveSmallIntegerField(default=1)),
                ('booked_count', models.PositiveSmallIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=False, help_text='Manually block this slot regardless of booking count.')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_availabilities', to='trades.businessprofile')),
            ],
            options={
                'verbose_name': 'time slot availability',
                'verbose_name_plural': 'time slot availabilities',
                'ordering': ['date', 'timeslot'],
                'constraints': [models.UniqueConstraint(fields=('business', 'date', 'timeslot'), name='unique_timeslot_per_business')],
            },
        ),
    ]
