"""
Django settings for flowpro project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from logging.handlers import RotatingFileHandler

import dj_database_url
from decouple import Csv, config
from django.utils.text import slugify

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="change-me-for-local-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost", cast=Csv())
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://127.0.0.1:8000,http://localhost:8000",
    cast=Csv(),
)

# Reverse proxy and browser security settings. These default to local-dev safe
# values and are switched on through environment variables for production clones.
USE_X_FORWARDED_HOST = config("USE_X_FORWARDED_HOST", default=False, cast=bool)
USE_X_FORWARDED_PORT = config("USE_X_FORWARDED_PORT", default=False, cast=bool)
SECURE_PROXY_SSL_HEADER_ENABLED = config(
    "SECURE_PROXY_SSL_HEADER", default=False, cast=bool
)
if SECURE_PROXY_SSL_HEADER_ENABLED:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = config("SECURE_SSL_REDIRECT", default=False, cast=bool)
SESSION_COOKIE_SECURE = config("SESSION_COOKIE_SECURE", default=False, cast=bool)
CSRF_COOKIE_SECURE = config("CSRF_COOKIE_SECURE", default=False, cast=bool)
SECURE_HSTS_SECONDS = config("SECURE_HSTS_SECONDS", default=0, cast=int)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False, cast=bool
)
SECURE_HSTS_PRELOAD = config("SECURE_HSTS_PRELOAD", default=False, cast=bool)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = config(
    "SECURE_REFERRER_POLICY", default="same-origin"
)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = config("CSRF_COOKIE_HTTPONLY", default=False, cast=bool)
X_FRAME_OPTIONS = config("X_FRAME_OPTIONS", default="DENY")

DATA_UPLOAD_MAX_MEMORY_SIZE = config(
    "DATA_UPLOAD_MAX_MEMORY_SIZE", default=25 * 1024 * 1024, cast=int
)
FILE_UPLOAD_MAX_MEMORY_SIZE = config(
    "FILE_UPLOAD_MAX_MEMORY_SIZE", default=10 * 1024 * 1024, cast=int
)
FILE_UPLOAD_PERMISSIONS = 0o644


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trades',
    'invoice',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flowpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flowpro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config(
    "DATABASE_URL",
    default="postgres://postgres:postgres@localhost:5432/flowpro_db",
)
DATABASES = {
    "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

EMAIL_PROVIDER = config("EMAIL_PROVIDER", default="console").lower()
EMAIL_PROVIDER_DEFAULTS = {
    "console": {
        "backend": "django.core.mail.backends.console.EmailBackend",
        "host": "",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "sender_net": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "smtp.sender.net",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "google_workspace": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "smtp.gmail.com",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "google_workspace_relay": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "smtp-relay.gmail.com",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "custom_smtp": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
}
EMAIL_DEFAULTS = EMAIL_PROVIDER_DEFAULTS.get(
    EMAIL_PROVIDER, EMAIL_PROVIDER_DEFAULTS["console"]
)

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="website@example.com")
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
ADMIN_NOTIFICATION_EMAIL = config("ADMIN_NOTIFICATION_EMAIL", default="")

# Error email recipients. Set ADMIN_NAME and ADMIN_EMAIL in .env.
# Django emails these addresses on 500 errors when DEBUG=False.
ADMIN_NAME = config("ADMIN_NAME", default="")
ADMIN_EMAIL = config("ADMIN_EMAIL", default="")
ADMINS = [(ADMIN_NAME, ADMIN_EMAIL)] if ADMIN_NAME and ADMIN_EMAIL else []

if EMAIL_PROVIDER == "custom_smtp":
    EMAIL_BACKEND = config("EMAIL_BACKEND", default=EMAIL_DEFAULTS["backend"])
    EMAIL_HOST = config("EMAIL_HOST", default=EMAIL_DEFAULTS["host"])
else:
    EMAIL_BACKEND = EMAIL_DEFAULTS["backend"]
    EMAIL_HOST = EMAIL_DEFAULTS["host"]
EMAIL_PORT = config("EMAIL_PORT", default=EMAIL_DEFAULTS["port"], cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=EMAIL_DEFAULTS["use_tls"], cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=EMAIL_DEFAULTS["use_ssl"], cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=20, cast=int)

# Trade-agnostic configuration
# Comma-separated list of service choices shown on booking/invoice forms.
# Override in .env per trade, e.g. SERVICE_CHOICES=Kitchen Fitting,Decking
_SERVICE_CHOICES_DEFAULT = [
    ("leaking_pipe", "Leaking Pipe"),
    ("blocked_drain", "Blocked Drain"),
    ("water_heater", "Water Heater"),
    ("toilet_repair", "Toilet Repair"),
    ("burst_pipe", "Burst Pipe"),
    ("bathroom_kitchen", "Bathroom / Kitchen"),
    ("gas_plumbing", "Gas Plumbing"),
    ("general", "General Maintenance"),
    ("other", "Other"),
]


def _load_service_choices():
    raw = config("SERVICE_CHOICES", default="")
    if not raw:
        return _SERVICE_CHOICES_DEFAULT
    items = [s.strip() for s in raw.split(",") if s.strip()]
    choices = []
    seen = set()
    for item in items:
        base_value = slugify(item).replace("-", "_")[:32] or "service"
        value = base_value
        suffix = 2
        while value in seen:
            suffix_text = f"_{suffix}"
            value = f"{base_value[:32 - len(suffix_text)]}{suffix_text}"
            suffix += 1
        seen.add(value)
        choices.append((value, item))
    return choices


SERVICE_CHOICES = _load_service_choices()


def get_service_choices():
    return _load_service_choices()


# Set to "UK" to enforce UK phone number and postcode validation on
# booking and invoice forms. Leave blank or set to another value for
# international mode (no phone/postcode regex enforced).
COUNTRY = config("COUNTRY", default="UK")

# Cache
# https://docs.djangoproject.com/en/5.2/topics/cache/
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.db.DatabaseCache",
        "LOCATION": "django_cache",
    }
}

# Rate limiting
# Format: "count/period" where period is s (seconds), m (minutes), h (hours), d (days).
# Example: BOOKING_RATE_LIMIT=5/m means 5 POSTs per minute per IP.
# Leave blank or unset to disable rate limiting.
BOOKING_RATE_LIMIT = config("BOOKING_RATE_LIMIT", default="", cast=str)

# Logging
# https://docs.djangoproject.com/en/5.2/topics/logging/
LOG_LEVEL = config("LOG_LEVEL", default="INFO")
LOGS_DIR = BASE_DIR / "logs"
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "formatters": {
        "verbose": {
            "format": "[%(asctime)s] %(levelname)s %(name)s %(message)s",
            "datefmt": "%Y-%m-%d %H:%M:%S",
        },
        "simple": {
            "format": "%(levelname)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
            "filters": ["require_debug_false"],
        },
        "file": {
            "level": LOG_LEVEL,
            "class": "logging.handlers.RotatingFileHandler",
            "filename": str(LOGS_DIR / "django.log"),
            "maxBytes": 5 * 1024 * 1024,  # 5 MB
            "backupCount": 3,
            "formatter": "verbose",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
        },
    },
    "root": {
        "handlers": ["console", "file"],
        "level": "WARNING",
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file", "mail_admins"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
        "trades": {
            "handlers": ["console", "file"],
            "level": LOG_LEVEL,
            "propagate": False,
        },
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
