"""
Django settings for flowpro project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY", default="change-me-for-local-development-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="127.0.0.1,localhost", cast=Csv())
CSRF_TRUSTED_ORIGINS = config(
    "CSRF_TRUSTED_ORIGINS",
    default="http://127.0.0.1:8000,http://localhost:8000",
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'trades',
    'invoice',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'flowpro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flowpro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASE_URL = config(
    "DATABASE_URL",
    default="postgres://postgres:postgres@localhost:5432/flowpro_db",
)
DATABASES = {
    "default": dj_database_url.parse(DATABASE_URL, conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / "media"

EMAIL_PROVIDER = config("EMAIL_PROVIDER", default="console").lower()
EMAIL_PROVIDER_DEFAULTS = {
    "console": {
        "backend": "django.core.mail.backends.console.EmailBackend",
        "host": "",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "sender_net": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "smtp.sender.net",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "google_workspace": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "smtp.gmail.com",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "google_workspace_relay": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "smtp-relay.gmail.com",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
    "custom_smtp": {
        "backend": "django.core.mail.backends.smtp.EmailBackend",
        "host": "",
        "port": 587,
        "use_tls": True,
        "use_ssl": False,
    },
}
EMAIL_DEFAULTS = EMAIL_PROVIDER_DEFAULTS.get(
    EMAIL_PROVIDER, EMAIL_PROVIDER_DEFAULTS["console"]
)

DEFAULT_FROM_EMAIL = config("DEFAULT_FROM_EMAIL", default="website@example.com")
SERVER_EMAIL = config("SERVER_EMAIL", default=DEFAULT_FROM_EMAIL)
ADMIN_NOTIFICATION_EMAIL = config("ADMIN_NOTIFICATION_EMAIL", default="")

if EMAIL_PROVIDER == "custom_smtp":
    EMAIL_BACKEND = config("EMAIL_BACKEND", default=EMAIL_DEFAULTS["backend"])
    EMAIL_HOST = config("EMAIL_HOST", default=EMAIL_DEFAULTS["host"])
else:
    EMAIL_BACKEND = EMAIL_DEFAULTS["backend"]
    EMAIL_HOST = EMAIL_DEFAULTS["host"]
EMAIL_PORT = config("EMAIL_PORT", default=EMAIL_DEFAULTS["port"], cast=int)
EMAIL_USE_TLS = config("EMAIL_USE_TLS", default=EMAIL_DEFAULTS["use_tls"], cast=bool)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", default=EMAIL_DEFAULTS["use_ssl"], cast=bool)
EMAIL_HOST_USER = config("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD", default="")
EMAIL_TIMEOUT = config("EMAIL_TIMEOUT", default=20, cast=int)

# Trade-agnostic configuration
# Comma-separated list of service choices shown on booking/invoice forms.
# Override in .env per trade, e.g. SERVICE_CHOICES=Kitchen Fitting,Decking
_SERVICE_CHOICES_DEFAULT = [
    ("leaking_pipe", "Leaking Pipe"),
    ("blocked_drain", "Blocked Drain"),
    ("water_heater", "Water Heater"),
    ("toilet_repair", "Toilet Repair"),
    ("burst_pipe", "Burst Pipe"),
    ("bathroom_kitchen", "Bathroom / Kitchen"),
    ("gas_plumbing", "Gas Plumbing"),
    ("general", "General Maintenance"),
    ("other", "Other"),
]


def _load_service_choices():
    raw = config("SERVICE_CHOICES", default="")
    if not raw:
        return _SERVICE_CHOICES_DEFAULT
    items = [s.strip() for s in raw.split(",") if s.strip()]
    return [(s.lower().replace(" ", "_").replace("/", "_"), s) for s in items]


SERVICE_CHOICES = property(lambda _: _load_service_choices())  # callable ref


def get_service_choices():
    return _load_service_choices()


# Set to "UK" to enforce UK phone number and postcode validation on
# booking and invoice forms. Leave blank or set to another value for
# international mode (no phone/postcode regex enforced).
COUNTRY = config("COUNTRY", default="UK")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
