# Generated by Django 5.2.13 on 2026-05-03 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trades', '0006_bookingimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('client_name', models.CharField(max_length=120)),
                ('client_phone', models.CharField(max_length=32)),
                ('client_email', models.EmailField(blank=True, max_length=254)),
                ('client_address', models.CharField(max_length=255)),
                ('client_postcode', models.CharField(max_length=16)),
                ('service_type', models.CharField(choices=[('leaking_pipe', 'Leaking Pipe'), ('blocked_drain', 'Blocked Drain'), ('water_heater', 'Water Heater'), ('toilet_repair', 'Toilet Repair'), ('burst_pipe', 'Burst Pipe'), ('bathroom_kitchen', 'Bathroom / Kitchen'), ('gas_plumbing', 'Gas Plumbing'), ('general', 'General Maintenance'), ('other', 'Other')], max_length=32)),
                ('job_description', models.TextField()),
                ('labour_description', models.TextField(blank=True)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('materials_description', models.TextField(blank=True)),
                ('materials_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('sent', 'Sent'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_enquiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='trades.bookingenquiry')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trades.businessprofile')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='invoice/images/')),
                ('image_type', models.CharField(choices=[('before', 'Before'), ('after', 'After')], max_length=8)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'invoice image',
                'verbose_name_plural': 'invoice images',
                'ordering': ['image_type', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('warranty_info', models.CharField(blank=True, max_length=300)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'invoice product',
                'verbose_name_plural': 'invoice products',
                'ordering': ['id'],
            },
        ),
    ]
